### ISSUE TITLE
Set text to editor

### ISSUE THREAD

**Issue by aqitmalinzda** [onecode369/WYSIWYG#1]
Hello, I have successfully saved the text results to the database, but how do I set the text to the editor again?

**Comment by onecode369** [comment]
the string which you have saved in database will be html format . Then retrieve the data and insert it WYSIWYG by setCode function.

**Comment by samarthgarg0622** [comment]
@aqitmalinzda can you please help me out how did you managed to save the text to database?

**Comment by samarthgarg0622** [comment]
> Hello, I have successfully saved the text results to the database, but how do I set the text to the editor again?
 can you please help me out how did you managed to save the text to database?

**Comment by samarthgarg0622** [comment]
Hey @onecode369, I am unable to set a string in editor using setCode function, can you help me out with it please?

**Comment by isaacmaxparker** [comment]
Do you have an example of how this setCode Function would work? Because from what I can see it doesn't take a parameter.

**Comment by isaacmaxparker** [comment]
For anyone else who has this error I finally found it: 

wysiwygEditor.html = <YOUR HTML STRING>
